### ISSUE TITLE
Ward

### ISSUE THREAD

**Issue by jvandg** [LukasCBossert/ijsra#13]

**Comment by DevinWard** [comment]
Small problem with author's affiliations: There should be a double dagger next to the single dagger beside the University of Cambridge affiliation.  I fixed this by adding it manually, but maybe (Lukas) you don't want it this way.

If it matters, all of the photos are from Michael.

I added links to a bunch of the hashtags.  I opted not to link all of the students, because I realized we did not have their permission.

**Comment by LukasCBossert** [comment]
1. `\def\affiltwoauthor{†‡}%<---- paste the symbol of the authors into {}` this works. 

2. `{\normalfont\scriptsize \\ \copyright\ by \authortwo}`

**Comment by LukasCBossert** [comment]
@jvandg I think this article is ready for proof reading. I let you change the status (label) and send the pdf-link to the author (I know, this is @DevinWard )

**Comment by LukasCBossert** [comment]
@DevinWard will you proof the article. I think it is fine so far - so final check from your side as author.

**Comment by DevinWard** [comment]
Thanks!  I'll send it to my coauthors just to be sure it's seen by fresh eyes.

**Comment by DevinWard** [comment]
I have had approval from both of my coauthors, so this is all set.  Thanks guys!

**Comment by LukasCBossert** [comment]
Perfect. One more done.

**Comment by LukasCBossert** [comment]
@DevinWard are you happy with "dlward11 AT gmail.com" as your contact-email-address for the paper - it has been missing.

**Comment by DevinWard** [comment]
I changed my email address to my new Toronto email 👍
